language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t msbyte/react-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true msbyte/react-fullstack-app npm run test

after_success:
  - docker build -t msbyte/docker-frontend ./frontend
  - docker build -t msbyte/docker-backend ./backend
  - docker build -t msbyte/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push msbyte/docker-frontend
  - docker push msbyte/docker-backend
  - docker push msbyte/docker-nginx
